name: dutydash
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  fluid_bottom_nav_bar: ^1.4.0
  curved_navigation_bar: ^1.0.3
  bottom_navy_bar: ^6.0.0
  animated_bottom_navigation_bar: ^1.3.3
  google_nav_bar: ^5.0.6
  datetime_picker_formfield: ^2.0.0
  http: '>=0.12.2 <1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
